workspace_root: &workspace_root
  /go/src/github.com/gruntwork-io/package-lambda

defaults: &defaults
  working_directory: *workspace_root
  docker:
  - image: 087285199408.dkr.ecr.us-east-1.amazonaws.com/circle-ci-test-image-base:latest

version: 2
jobs:
  install_dependencies:
    <<: *defaults
    steps:
    - checkout
    - attach_workspace:
        at: *workspace_root
    - restore_cache:
        keys:
        - dep-{{ checksum "test/Gopkg.lock" }}
    - run: cd test && dep ensure
    - save_cache:
        key: dep-{{ checksum "test/Gopkg.lock" }}
        paths: /go/src/github.com/gruntwork-io/package-lambda/test/vendor
    - persist_to_workspace:
        root: *workspace_root
        paths: test/vendor

  test:
    <<: *defaults
    steps:
    - checkout
    - attach_workspace:
        at: *workspace_root
    - run:  run-go-tests --circle-ci-2 --path test

workflows:
  version: 2
  run-tests:
    jobs:
    - install_dependencies:
        filters:
          tags:
            only: /^v.*/
    - test:
        requires:
        - install_dependencies
        filters:
          tags:
            only: /^v.*/
  nightly:
    triggers:
    - schedule:
        cron: "0 6 * * *"
        filters:
          branches:
            only: master
    jobs:
    - install_dependencies
    - test:
        requires:
        - install_dependencies
        