defaults: &defaults
  machine:
    enabled: true
    image: "ubuntu-1604:201903-01"
  environment:
    GRUNTWORK_INSTALLER_VERSION: v0.0.23
    TERRATEST_LOG_PARSER_VERSION: v0.13.13
    MODULE_CI_VERSION: v0.18.4
    TERRAFORM_VERSION: 0.13.3
    TERRAGRUNT_VERSION: NONE
    PACKER_VERSION: NONE


version: 2.0
jobs:
  test aws:
    <<: *defaults
    steps:
    - checkout
    - run: &install_gruntwork_tooling
        name: install gruntwork tooling
        command: |
          curl -Ls https://raw.githubusercontent.com/gruntwork-io/gruntwork-installer/master/bootstrap-gruntwork-installer.sh | bash /dev/stdin --version "${GRUNTWORK_INSTALLER_VERSION}"
          gruntwork-install --module-name "gruntwork-module-circleci-helpers" --repo "https://github.com/gruntwork-io/module-ci" --tag "${MODULE_CI_VERSION}"
          gruntwork-install --binary-name "terratest_log_parser" --repo "https://github.com/gruntwork-io/terratest" --tag "${TERRATEST_LOG_PARSER_VERSION}"
          configure-environment-for-gruntwork-module \
            --terraform-version ${TERRAFORM_VERSION} \
            --terragrunt-version ${TERRAGRUNT_VERSION} \
            --packer-version ${PACKER_VERSION} \
            --go-src-path ./test

    # Run pre-commit hooks and fail the build if any hook finds required changes.
    - run:
        name: run precommit
        command: |
          # Oct 26, 2019: Install the last known working version of pre-commit. Also, we have to pin the version of
          # transitive dependencies that are being pulled in which released new versions that are no longer compatible
          # with any python < 3.6.
          pyenv global 3.5.2
          pip install pre-commit==1.21.0 cfgv==2.0.1 zipp==1.1.0
          pre-commit install
          pre-commit run --all-files

    - run:
        name: run tests
        command: |
            mkdir -p /tmp/logs
            run-go-tests --path test --timeout 1h | tee /tmp/logs/all.log
        no_output_timeout: 3600s

    - run:
        command: terratest_log_parser --testlog /tmp/logs/all.log --outputdir /tmp/logs
        when: always
    - store_artifacts:
        path: /tmp/logs
    - store_test_results:
        path: /tmp/logs

workflows:
  version: 2
  build-and-test:
    jobs:
    - test aws:
        filters:
          tags:
            only: /^v.*/
